### ISSUE TITLE
Errors when fetching Identity API

### ISSUE THREAD

**Issue by scmoreira** [mParticle/mparticle-web-sdk#213] opened 2022-02-15 11:20 UTC
Hello, 
I am getting this error: `Error sending event to mParticle servers` that says that failed to fetch. 
I couldn't find any possible reason for this error, as it is calling the Identity.identify method properly, but sometimes after doing it, the error appears. I didn't find any common parameter between them, the browsers are Chrome, Safari, Opera, on Mac and Windows too. 
I am getting also another error:` Error parsing JSON response from Identity server`, when trying to read properties `mpid` and `initForwarders`. But, also here, I am passing the `userIdentities` object and preventing the value to be undefined.
Did you get any similar errors? This could be related to users not allowing cookies?

**Comment by rmi22186** [comment] 2022-02-15 14:47
Hi @scmoreira!  Nothing off the top of my head sounds obvious. Can you actually file this via your customer success manager with very specific reproduction steps to get this routed properly?  We have a team that helps customers debug issues like this.  I'm going to close this comment for now since you should go through that method to get this resolved. 

Thanks!

**Closed by rmi22186** 2022-02-15 14:47 UTC
